### ISSUE TITLE
Ownership is expected

### ISSUE THREAD

**Issue by chrissng** [datagovsg/job-descriptions#5]
Not only we want to have a conducive environment for continuous learning, we also want our people to have a sense of ownership in their work. 

Build something you believe in and build it in the best possible way. Having an opinion on the work getting done and have great ideas on what's next.

**Comment by LoneRifle** [comment]
I feel that such wording conveys our desire for candidates that are willing to have a stake in the outcome of the things they are involved in, for better or worse. This also somewhat implies an appetite for risk, given that some of their opinions may not turn out to be helpful for the project.

**Comment by leesq** [comment]
I think we've successfully incorporated this sentiment in the iteration. I'll be closing this for now. Thanks everyone!
