### ISSUE TITLE
What is Actor Model? Is that necessary?

### ISSUE THREAD

**Issue by xkjyeah** [datagovsg/job-descriptions#7]

**Comment by LoneRifle** [comment]
It _might_. I think we could mitigate by supplying another example of a distributed computing concept to give people a broad idea of what we are looking for.

**Comment by leesq** [comment]
@LoneRifle any suggestions on a good concept to have?

**Comment by LoneRifle** [comment]
MapReduce perhaps? It seems to lend itself well to many problems even outside Spark/Hadoop/etc.

**Comment by LoneRifle** [comment]
... I'll put in a PR
